<?php

namespace AppBundle\Repository;

/**
 * ItemtypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemtypeRepository extends \Doctrine\ORM\EntityRepository
{
}
