<?php

namespace AppBundle\Repository;

/**
 * SellingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SellingRepository extends \Doctrine\ORM\EntityRepository
{
}
